alias pip='/usr/local/bin/pip3'
alias python='/usr/local/bin/python3'
alias xxd='hexyl'
alias sed='gsed'
alias cat='bat'
alias q='pbcopy'
alias qq='pbpaste'
alias t='twterm'
alias grep='rg -n'
alias vim='nvim'
alias top='procs --watch --insert TcpPort --sortd cpu'
alias ps='procs --color=disable --sorta pid'
alias cloc='tokei'
alias du='dust'
alias htop='btm'
alias dc='docker-compose'
