export LANG=en_US.UTF-8
export DISABLE_AUTO_UPDATE=true
export PATH=/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:$HOME/.nodebrew/current/bin:$HOME/.cargo/bin:$HOME/.original-scripts/bin:$HOME/.composer/vendor/bin:$HOME/bin:/usr/local/bin:/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
export GOPATH=$HOME/.go
export GO111MOD=on
export ENHANCD_FILTER="fzf --reverse --ansi"
export ENHANCD_DISABLE_DOT=1
export TSC_WATCHFILE=UseFsEventsWithFallbackDynamicPolling
export PS1="%~ $"
export DOCKER_CONTENT_TRUST=1
export OPENSSH="/usr/local/opt/openssh"
